### ISSUE TITLE
.params.issueId should be number

### ISSUE THREAD

**Issue by JohnLindahlTech** [vaparr/ha-overseerr#20]
I am getting the following log "warning" in `HomeAssistant@v2022.6.7` when using `ha-overseerr@v0.1.34` and I am running `Overseer@v1.29.1`

```
Unable to update Overseerr sensor: HTTP Error 400. Check SSL configuration. {'message': 'request.params.issueId should be number', 'errors': [{'path': '.params.issueId', 'message': 'should be number', 'errorCode': 'type.openapi.validation'}]}
```

And I have a `Overseerr Issues: Unknown` sensor.

This is a minor issue (pun kind of inteded) for me as I do not actively using the functionallity in Overseer, but I thought I would report what I am seeing.

**Comment by MrDrew514** [comment]
I'm currently getting the same error/warning. Trying to find a solution.

**Comment by vaparr** [comment]
Should be fixed in 0.1.35

**Comment by JohnLindahlTech** [comment]
Ok, thnx!
But I do have an issues-page in Overseerr so that makes me kind of confused, and it tells me I am on the latest release.

**Comment by vaparr** [comment]
Its been 4 months since the last Overseerr release, and i am on the develop branch, which has a lot of new features.  It didnt occur to me that the old (current) release build didn't have all them.

**Comment by JohnLindahlTech** [comment]
I have updated to 0.1.35, and still get errors and logs in my HA.
But again; I do not use the issues feature so feel free to close this one, as your comment got me intrigued and I will most probably jump on the dev-train of Overseer anyway.

But for full openness:
```
Warning.
Logger: homeassistant.helpers.entity_component
Source: helpers/entity_component.py:47
First occurred: 9:17:42 AM (41 occurrences)
Last logged: 3:57:42 PM

Forced update failed. Entity sensor.overseerr_issues not found.
```

```
Warning
Logger: custom_components.overseerr.sensor
Source: custom_components/overseerr/sensor.py:98
Integration: Overseerr ([documentation](https://github.com/vaparr/ha-overseerr), [issues](https://github.com/vaparr/ha-overseerr/issues))
First occurred: 1:57:45 PM (1 occurrences)
Last logged: 1:57:45 PM

Unable to update Overseerr sensor: Connection error. Check host configuration.
```

```
Error
Logger: homeassistant.components.sensor
Source: custom_components/overseerr/sensor.py:72
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 9:07:47 AM (1 occurrences)
Last logged: 9:07:47 AM

overseerr: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/sensor.py", line 72, in update
    self._state = issueCounts["open"]
TypeError: 'int' object is not subscriptable
```

**Comment by MrDrew514** [comment]
Getting the same exact error after the new release. Thank you @vaparr for the quick replies/support.

**Comment by MrDrew514** [comment]
I’m guessing this warning/error is affecting all the users. Not only you

**Comment by vaparr** [comment]
Published a new workaround in 0.1.36.  Let me know if it works, as i dont have the release version of overseerr currently installed.

**Comment by MrDrew514** [comment]
I tried to restart Hass and got an error; I'll log in my laptop soon to check that with more details. But it seems like the configuration became invalid. 

Logger: homeassistant.setup
Source: setup.py:162 
First occurred: 10:53:17 (1 occurrences) 
Last logged: 10:53:17

Setup failed for custom integration overseerr: Unable to import component: Exception importing custom_components.overseerr

**Comment by vaparr** [comment]
I pulled that release.  Re-issued .37.. Currently loading it now

**Comment by MrDrew514** [comment]
Im sorry for all the work it gives you, really! Switching to the dev version would fix this?
```

Logger: homeassistant.components.sensor
Source: custom_components/overseerr/sensor.py:74 
Integration: Capteur (documentation, issues) 
First occurred: 11:29:48 (1 occurrences) 
Last logged: 11:29:48

overseerr: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/sensor.py", line 74, in update
    for key in lastIssue:
TypeError: 'NoneType' object is not iterable

```

**Comment by vaparr** [comment]
It should.  But it would be nice if this worked on release as well! Im looking at that now

**Comment by MrDrew514** [comment]
I'd you're not getting any issue with the dev version, and it has new updates; I'll switch to it, maybe juste make a note in the frontpage. That would quickly fix that.

**Comment by MrDrew514** [comment]
No more warning/errors! I'll test it on my laptop, is the dev version still supported? Thank you!

**Comment by vaparr** [comment]
Awesome.  Im not sure if its "supported", but they've always helped me out on the overseerr discord when i was on dev.. Of course, once in a while there will be something broken, but its rare.

**Comment by MrDrew514** [comment]
I thought you edited the API part of the code to support the older version, and that it wouldn't not support the "new" dev-version api.

**Comment by vaparr** [comment]
ahh, no.. The code actually tries the new API first, then when it get an exception, it tries the workaround.

So the dev version is better supported than the release version

**Comment by MrDrew514** [comment]
I get it now. Have you tried the request service? I'm getting this error unfortunately. But I will try the dev version. 

```

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/overseerr/__init__.py:125 
Integration: Overseerr (documentation, issues) 
First occurred: 12:16:40 (2 occurrences) 
Last logged: 12:18:17

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/__init__.py", line 125, in submit_movie_request
    movie = movies[0]
KeyError: 0

```

**Comment by vaparr** [comment]
what movie did you search for? I think there may be a bug if the movie was not found

**Comment by vaparr** [comment]
nevermind.. I was able to repro.. Ill have a fix shortly.

**Comment by vaparr** [comment]
0.1.40 released.. i think that should fix this

**Comment by vaparr** [comment]
I think 0.1.41 should fix this

**Comment by MrDrew514** [comment]
I'll try as soon as I get home

**Comment by JohnLindahlTech** [comment]
Works nicely for me now, no log messages in HA, regardless if I run latest or develop for Overseer!

Thnx for excellent responsetimes, @vaparr!

@MrDrew514 I will now fully leave this issue so to speak so feel free to close it when/if your last hickup is solved.

**Comment by MrDrew514** [comment]
So, i now installed the dev branch of overseerr. I still get an error when requesting a movie. Correct me if I'm wrong but the way of requesting a movie is:

```
service: overseerr.submit_movie_request
data:
  name: the incredible hulk
```

**Comment by vaparr** [comment]
That is correct.. Im seeing that too.

**Comment by vaparr** [comment]
Just published a new release.. Seems to work for me

**Comment by MrDrew514** [comment]
Seems like everything is fixed for me! Awesome man, I owe you a beer.

**Comment by vaparr** [comment]
Awesome. Closing issue. Feel free to open another one if you want to chat some more :)
